/**
 * The body map — "where does it hurt", answered by touching a body.
 *
 * Two flat figures, front and back, SIDE BY SIDE in the clinical
 * pain-drawing tradition — both on screen at once, because a toggle
 * hides half the body and a sore lower back should never be a mode
 * away. Generated by tools/make-body.js so each silhouette and its
 * touch regions share one 100×200 coordinate system. Every region
 * maps to a location id the record stores; the map is a better hand
 * for the same vocabulary, never a second data model.
 *
 * A marked region wears THE CHECK-IN'S OWN pain colour — the intensity
 * chosen one step earlier. Colour means pain here as everywhere; the
 * map only ever answers where.
 *
 * Three interactions, each with its own honesty rule:
 *  - TAP toggles a region (and VoiceOver gets a labelled button).
 *  - A STROKE paints every region it crosses, and its START POINT
 *    picks the direction: begin on an unmarked region and the sweep
 *    adds; begin on a marked one and it erases. One stroke, one
 *    direction — fixed at touch-down, so a wobble on the way back can
 *    never undo what the same stroke just did. Gesture Handler's pan,
 *    the machinery the slider trusts, in the figure's own frame.
 *  - ALL OVER is the whole body: stored as the one id the record has
 *    always used, drawn as every region lit. Individual marks are
 *    redundant beside it, so choosing it clears them, and touching one
 *    place afterwards starts precision over from that place.
 *
 * The selection reads back as TAGS under the figure — full words that
 * wrap, never a cropped column, pairs collapsed to their plain plural
 * ("Shoulders": on a body map, both marked already says both). A tag
 * is also the way to take a mark back.
 */
import React, { useEffect, useRef } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, {
  FadeIn, cancelAnimation, runOnJS, useAnimatedStyle, useSharedValue,
  withRepeat, withTiming,
} from 'react-native-reanimated';
import * as Haptics from 'expo-haptics';
import { useReduceMotion } from './motion';
import { LOC_NAMES, readLocParts } from './model';
import { color, font } from './theme';

/* Each silhouette and its regions share ONE coordinate system: the
   100 × 200 design space tools/make-body.js renders the figures from.
   Change a figure there and the numbers here, together. */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const BODY_FRONT = require('../assets/body-front.png');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const BODY_BACK = require('../assets/body-back.png');
/* a white radial gaussian, tinted at use — see tools/make-body.js */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const GLOW = require('../assets/glow.png');

/* A figure's ink spans x ≈ 19…81; the rest of its 100-unit box is
   empty margin. The two boxes therefore OVERLAP by TUCK units — only
   whitespace overlaps, and the bodies get that room instead, which is
   the whole difference between two small figures and two large ones on
   a phone. SPLIT is the line between them for touch: past every front
   fingertip, short of every back one. */
const TUCK = 30;
const SPAN = 200 - TUCK;
const BACK_OFF = 100 - TUCK;
const SPLIT = 85;

interface Region {
  id: string;          // a LOC_NAMES id — several regions may share one
  side?: 'Left' | 'Right';
  x: number; y: number; w: number; h: number; r: number;
}

/* Left in these tables means the figure's anatomical left, which sits
   on the VIEWER'S right in the front view; the back view mirrors,
   exactly as a body does. Small joints lean on hitSlop — a sore wrist
   deserves a target bigger than a wrist. */
const mirrorX = (r: Omit<Region, 'id' | 'side'>) => ({ ...r, x: 100 - r.x - r.w });
const pairL = (idL: string, idR: string, r: Omit<Region, 'id' | 'side'>, front: boolean): Region[] => [
  { id: front ? idR : idL, side: front ? 'Right' : 'Left', ...r },
  { id: front ? idL : idR, side: front ? 'Left' : 'Right', ...mirrorX(r) },
];

function sideRegions(front: boolean): Region[] {
  const p = (l: string, r: string, box: Omit<Region, 'id' | 'side'>) => pairL(l, r, box, front);
  return ([] as Region[]).concat(
    p('shoulderL', 'shoulderR', { x: 28, y: 26.5, w: 16, h: 11, r: 5 }),
    p('armL', 'armR', { x: 22, y: 38, w: 11, h: 17, r: 5 }),
    p('elbowL', 'elbowR', { x: 21.5, y: 55, w: 11, h: 9, r: 4.5 }),
    p('forearmL', 'forearmR', { x: 21, y: 64, w: 11, h: 13, r: 4.5 }),
    p('wristL', 'wristR', { x: 20.5, y: 77, w: 10.5, h: 7, r: 3.5 }),
    p('handL', 'handR', { x: 18.5, y: 84, w: 11, h: 13, r: 5 }),
    p('hipL', 'hipR', { x: 35, y: 72, w: 15, h: 21, r: 7 }),
    p('thighL', 'thighR', { x: 36, y: 93, w: 13.5, h: 34, r: 6 }),
    p('kneeL', 'kneeR', { x: 37, y: 127, w: 12.5, h: 15, r: 6 }),
    p('calfL', 'calfR', { x: 38, y: 142, w: 11.5, h: 26, r: 5.5 }),
    p('ankleL', 'ankleR', { x: 38.5, y: 168, w: 11, h: 8, r: 4 }),
    p('footL', 'footR', { x: 34, y: 176, w: 15.5, h: 13, r: 6 }),
  );
}

const CENTRE: Region[] = [
  { id: 'head', x: 40, y: 1, w: 20, h: 20, r: 10 },
  { id: 'neck', x: 43, y: 20, w: 14, h: 8, r: 3.5 },
];

const FRONT: Region[] = CENTRE.concat(sideRegions(true), [
  { id: 'chest', x: 37.5, y: 36, w: 25, h: 20, r: 7 },
  { id: 'belly', x: 37.5, y: 56, w: 25, h: 17, r: 7 },
]);

const BACK: Region[] = CENTRE.concat(sideRegions(false), [
  { id: 'upperBack', x: 37.5, y: 36, w: 25, h: 20, r: 7 },
  { id: 'lowerBack', x: 37.5, y: 56, w: 25, h: 17, r: 7 },
]);

/** every place the body knows, both views — what an erase stroke works
 *  against when it starts from "all over" */
const ALL_IDS: string[] = (() => {
  const seen: Record<string, true> = {};
  const out: string[] = [];
  FRONT.concat(BACK).forEach((r) => {
    if (!seen[r.id]) { seen[r.id] = true; out.push(r.id); }
  });
  return out;
})();

export interface BodyMapProps {
  selected: string[];
  /** the whole next selection — the map owns toggle, stroke and
   *  all-over arithmetic so its rules live in one place */
  onChange: (next: string[]) => void;
  /** the check-in's pain colour — what a marked region wears */
  tint: string;
  /** legible ink on that colour, for the tags that sit on it */
  ink: string;
  /** the space the step actually has; the figure sizes itself to fit */
  containerWidth: number;
  containerHeight: number;
}

/** generous hit padding during a STROKE, in design units — a sweep down
 *  the arm should catch the wrist band without aiming. Taps keep the
 *  exact rects (plus hitSlop); only the moving finger gets the slack. */
const STROKE_PAD = 1.6;

export default function BodyMap({
  selected, onChange, tint, ink, containerWidth, containerHeight,
}: BodyMapProps) {
  /* fit: captions ~26pt, actions ~32pt, tag line ~54pt; the figures
     take everything else. Two bodies share the width, so the floor is
     low — a narrow phone gets two smaller figures, never one cropped
     one. */
  const k = Math.max(1.0, Math.min(
    (containerHeight - 128) / 200,
    (containerWidth - 8) / SPAN
  ));
  const figW = 100 * k;
  const backOff = BACK_OFF * k;
  const width = SPAN * k;
  const allSelected = ALL_IDS.every((id) => selected.indexOf(id) >= 0);

  /* A legacy 'allOver' arriving through the prefill (an older entry
     said it) becomes the explicit whole body it always meant — Select
     all now records every named place rather than one umbrella id, so
     an "everywhere except…" erase reads correctly in the record too.
     Old stored entries keep their allOver id and still display. */
  useEffect(() => {
    if (selected.indexOf('allOver') >= 0) onChange(ALL_IDS.slice());
  }, [selected]);

  const haptic = () => Haptics.selectionAsync().catch(() => {});

  const toggle = (id: string) => {
    haptic();
    onChange(selected.indexOf(id) >= 0
      ? selected.filter((x) => x !== id)
      : selected.concat(id));
  };

  const toggleSelectAll = () => {
    haptic();
    onChange(allSelected ? [] : ALL_IDS.slice());
  };

  /* ── the pulse ────────────────────────────────────────────
     One shared clock; every glow breathes on it together — marks
     softening in unison reads as one body, not as competing alarms.
     The breath is in the BLUR: the wash spreads a little wider and
     dims as it spreads, then draws back in. Slight on purpose, and a
     slow there-and-back, so it never reads as a blinking alert. Held
     mid-breath under Reduce Motion. */
  const rm = useReduceMotion();
  const pulse = useSharedValue(0);
  useEffect(() => {
    if (rm) { cancelAnimation(pulse); pulse.value = 0.5; return; }
    pulse.value = 0;
    pulse.value = withRepeat(withTiming(1, { duration: 2600 }), -1, true);
  }, [rm]);
  /* never fully opaque — the glow is a wash over the figure, and the
     outline ghosting through is what keeps it a body, not a heatmap */
  const glowStyle = useAnimatedStyle(() => ({
    opacity: 0.92 - pulse.value * 0.18,
    transform: [{ scale: 1 + pulse.value * 0.1 }],
  }));

  /* ── the stroke ───────────────────────────────────────────
     A ref mirrors the selection so a fast sweep is not throttled by
     render round-trips: each region paints against the stroke's own
     running state, and every change still flows up through onChange.

     The MODE is fixed at touch-down: starting on a marked region makes
     this an erasing sweep, on an unmarked one an adding sweep. An erase
     that starts from "all over" first materialises the whole body as
     explicit places and then removes what the finger crosses — "all
     over except my right knee" is a real thing to say, and this is the
     only honest way to say it. */
  const strokeSel = useRef<string[]>(selected);
  strokeSel.current = selected;
  const strokeMode = useRef<'add' | 'erase'>('add');
  /* one canvas, two figures: the gap's midline decides which body a
     point belongs to, so a single stroke can sweep from a front thigh
     across to the lower back without lifting */
  const regionAt = (x: number, y: number): string | null => {
    const pad = STROKE_PAD * k;
    const scan = (list: Region[], px: number): string | null => {
      for (const rg of list) {
        if (px >= rg.x * k - pad && px <= (rg.x + rg.w) * k + pad
          && y >= rg.y * k - pad && y <= (rg.y + rg.h) * k + pad) return rg.id;
      }
      return null;
    };
    return x < SPLIT * k ? scan(FRONT, x) : scan(BACK, x - backOff);
  };
  const beginStroke = (x: number, y: number) => {
    const id = regionAt(x, y);
    strokeMode.current = id && strokeSel.current.indexOf(id) >= 0 ? 'erase' : 'add';
    paintAt(x, y);
  };
  const paintAt = (x: number, y: number) => {
    const id = regionAt(x, y);
    if (!id) return;
    const cur = strokeSel.current;
    const has = cur.indexOf(id) >= 0;
    if (strokeMode.current === 'add' ? has : !has) return;
    const next = strokeMode.current === 'add'
      ? cur.concat(id)
      : cur.filter((x2) => x2 !== id);
    strokeSel.current = next;
    haptic();
    onChange(next);
  };
  const pan = Gesture.Pan()
    .minDistance(12)
    .onStart((e) => { 'worklet'; runOnJS(beginStroke)(e.x, e.y); })
    .onUpdate((e) => { 'worklet'; runOnJS(paintAt)(e.x, e.y); });

  /* Tags in ADD ORDER, newest rightmost — the selection array already
     records the order marks were made, so a stroke down the arm files
     Shoulder, Elbow, Wrist into the row as the finger passes. The row
     follows the newest tag so its arrival is always seen. */
  const parts = readLocParts(selected).slice().sort((a, b) => {
    const at = (p: { ids: string[] }) =>
      Math.max.apply(null, p.ids.map((id) => selected.indexOf(id)));
    return at(a) - at(b);
  });
  const tagScroll = useRef<ScrollView>(null);
  const prevCount = useRef(parts.length);
  useEffect(() => {
    if (parts.length > prevCount.current) {
      tagScroll.current?.scrollToEnd({ animated: true });
    }
    prevCount.current = parts.length;
  }, [parts.length]);

  /* A mark is a WASH WITH NO EDGE: the gaussian sprite, tinted with
     the check-in's pain colour and stretched over the region, so a
     thigh reads as a long streak and a shoulder as a round bloom, and
     neighbouring marks bleed into one another the way a hurting area
     actually spreads. Nothing here has a border to catch the eye.
     Glows are drawn as their own layer BENEATH every touch target, so
     what lights up can spill past the rectangle that was touched.
     A shared id (head, neck) lights on both figures at once, because
     it is one place, not two answers. */
  const glow = (list: Region[], off: number, tag: string) =>
    list.map((rg, i) => {
      if (selected.indexOf(rg.id) < 0) return null;
      /* the sprite is invisible by its own rim, so it is drawn half
         again as large as the region: the bright middle covers the
         place, the falloff leaves it */
      const gw = rg.w * k * 1.5, gh = rg.h * k * 1.5;
      return (
        <Animated.Image
          key={'g' + tag + rg.id + i}
          source={GLOW}
          resizeMode="stretch"
          accessible={false}
          style={[
            {
              position: 'absolute',
              left: off + (rg.x + rg.w / 2) * k - gw / 2,
              top: (rg.y + rg.h / 2) * k - gh / 2,
              width: gw, height: gh,
              tintColor: tint,
            },
            glowStyle,
          ]}
        />
      );
    });

  /* Touch zones stay the full region rectangles. */
  const figure = (src: number, list: Region[], off: number, tag: string) => (
    <React.Fragment key={tag}>
      <Image
        source={src}
        style={{ position: 'absolute', left: off, width: figW, height: 200 * k }}
        resizeMode="stretch"
        accessible={false}
      />
      {glow(list, off, tag)}
      {list.map((rg, i) => {
        const on = selected.indexOf(rg.id) >= 0;
        return (
          <Pressable
            key={tag + rg.id + (rg.side || '') + i}
            onPress={() => toggle(rg.id)}
            hitSlop={rg.h < 10 ? 5 : 3}
            accessibilityRole="button"
            accessibilityState={{ selected: on }}
            accessibilityLabel={(LOC_NAMES[rg.id] || rg.id) + ', ' + tag + ' view'}
            accessibilityHint={on ? 'Removes this area' : 'Marks this area'}
            style={({ pressed }) => [
              {
                position: 'absolute',
                left: off + rg.x * k, top: rg.y * k,
                width: rg.w * k, height: rg.h * k,
                borderRadius: rg.r * k, borderCurve: 'continuous',
                alignItems: 'center', justifyContent: 'center',
              },
              /* the glow lives outside this view now, so press
                 feedback is the same faint wash either way: it says
                 "this is the place you are touching", not what will
                 happen to it */
              pressed && { backgroundColor: 'rgba(255,255,255,0.10)' },
            ]}
          />
        );
      })}
    </React.Fragment>
  );

  return (
    <View style={styles.wrap}>
      {/* Slack is split ABOVE and BELOW the figures rather than pooled
          into one gap. The figures are capped by width, not height —
          two bodies fixed at 100 × 200 each cannot grow into spare
          height — so on a tall phone there is always slack, and a
          single spacer put all of it in one place, which read as a
          hole in the middle of the step instead of as air. */}
      <View style={styles.slack} />

      <GestureDetector gesture={pan}>
        <View style={{ width, height: 200 * k, alignSelf: 'center', flexShrink: 0 }}>
          {figure(BODY_FRONT, FRONT, 0, 'front')}
          {figure(BODY_BACK, BACK, backOff, 'back')}
        </View>
      </GestureDetector>

      {/* quiet captions, not a control — with both bodies on screen
          the words only settle which is which */}
      <View style={[styles.captions, { width, alignSelf: 'center' }]}>
        <Text style={[styles.captionText, { left: 0, width: figW }]}
          allowFontScaling maxFontSizeMultiplier={1.3}>
          Front
        </Text>
        <Text style={[styles.captionText, { left: backOff, width: figW }]}
          allowFontScaling maxFontSizeMultiplier={1.3}>
          Back
        </Text>
      </View>

      <View style={styles.slack} />

      {/* whole-body actions on their own quiet line — text, not pills.
          Set to the FIGURES' width, not the screen's: they act on the
          canvas above, and at the screen edges they read as page
          buttons belonging to the step. */}
      <View style={[styles.actionsRow, { width, alignSelf: 'center' }]}>
        <Pressable
          onPress={() => { haptic(); onChange([]); }}
          hitSlop={8}
          accessibilityRole="button"
          accessibilityLabel="Clear all marked areas"
          style={({ pressed }) => pressed && { opacity: 0.6 }}
        >
          <Text style={styles.actionText} allowFontScaling maxFontSizeMultiplier={1.3}>
            Clear all
          </Text>
        </Pressable>
        <Pressable
          onPress={toggleSelectAll}
          hitSlop={8}
          accessibilityRole="button"
          accessibilityState={{ selected: allSelected }}
          accessibilityLabel="Select the whole body"
          style={({ pressed }) => pressed && { opacity: 0.6 }}
        >
          <Text
            style={[styles.actionText, allSelected && { fontWeight: '700' as const }]}
            allowFontScaling maxFontSizeMultiplier={1.3}
          >
            Select all
          </Text>
        </Pressable>
      </View>

      {/* ── the selection, as removable tags ────────────────
          Tags WRAP now, up to two lines, and scroll vertically beyond
          that. One sideways-scrolling line kept slicing tags at the
          edge and hid most of a dozen marks behind a gesture nobody
          was told about; two lines show the whole selection in the
          common case. The block shrinks before it ever pushes into the
          Save button below. Full words, pairs collapsed; a tag is the
          selection made legible AND the way to take it back. */}
      <ScrollView
        ref={tagScroll}
        showsVerticalScrollIndicator={false}
        style={styles.tagsScroll}
        contentContainerStyle={styles.tags}
        accessibilityLiveRegion="polite"
      >
        {parts.map((part) => (
          /* A new tag fades in — the arrival is the confirmation that
             the touch landed. Entering only: a layout transition on the
             siblings fought the block's own scroll-to-end and the two
             animations tore at each other. One mover at a time. */
          <Animated.View
            key={part.label}
            entering={FadeIn.duration(200)}
          >
            <Pressable
              onPress={() => {
                haptic();
                onChange(selected.filter((x) => part.ids.indexOf(x) < 0));
              }}
              accessibilityRole="button"
              accessibilityLabel={part.label + ', marked'}
              accessibilityHint="Removes this area"
              style={({ pressed }) => [
                styles.tag,
                { backgroundColor: tint, borderColor: 'rgba(255,255,255,0.3)' },
                pressed && { opacity: 0.7 },
              ]}
            >
              <Text
                style={[styles.tagText, { color: ink, fontWeight: '600' as const }]}
                allowFontScaling maxFontSizeMultiplier={1.3}
                numberOfLines={1}
              >
                {part.label}
              </Text>
            </Pressable>
          </Animated.View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { flex: 1, paddingBottom: 10 },
  /* the two halves of the leftover height; equal, so the figures sit
     centred in whatever the step has */
  slack: { flex: 1, minHeight: 0 },
  /* each caption is placed at its own figure's offset — the figures
     overlap their empty margins, so nothing evenly spaced would land
     under them */
  captions: { height: 20, marginTop: 6 },
  captionText: {
    position: 'absolute',
    color: color.textSecondary, fontSize: font.footnote, fontWeight: '600',
    textAlign: 'center',
  },
  actionsRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    marginTop: 10, minHeight: 28,
  },
  actionText: { color: color.tint, fontSize: font.footnote, fontWeight: '600' },
  /* Two lines of tags, then it scrolls: flexShrink lets the block give
     its height back when the step is short, so it can never push into
     the Save button, and the cap is generous enough that scaled-up type
     still shows two whole rows rather than two clipped ones. */
  tagsScroll: { marginTop: 8, flexGrow: 0, flexShrink: 1, maxHeight: 96 },
  tags: {
    flexDirection: 'row', flexWrap: 'wrap', gap: 8,
    alignItems: 'center', justifyContent: 'center',
    paddingHorizontal: 16, paddingBottom: 4,
  },
  tag: {
    minHeight: 36, paddingHorizontal: 14, justifyContent: 'center',
    borderRadius: 18, borderCurve: 'continuous', borderWidth: 1,
  },
  tagText: { color: color.textPrimary, fontSize: font.subheadline },
});
