/**
 * The body map — "where does it hurt", answered by touching a body.
 *
 * A flat figure, front and back, in the clinical pain-drawing
 * tradition, generated by tools/make-body.js so the silhouette and
 * these touch regions share one 100×200 coordinate system. Every
 * region maps to a location id the record stores; the map is a better
 * hand for the same vocabulary, never a second data model.
 *
 * A marked region wears THE CHECK-IN'S OWN pain colour — the intensity
 * chosen one step earlier. Colour means pain here as everywhere; the
 * map only ever answers where.
 *
 * Three interactions, each with its own honesty rule:
 *  - TAP toggles a region (and VoiceOver gets a labelled button).
 *  - A STROKE paints every region it crosses, and its START POINT
 *    picks the direction: begin on an unmarked region and the sweep
 *    adds; begin on a marked one and it erases. One stroke, one
 *    direction — fixed at touch-down, so a wobble on the way back can
 *    never undo what the same stroke just did. Gesture Handler's pan,
 *    the machinery the slider trusts, in the figure's own frame.
 *  - ALL OVER is the whole body: stored as the one id the record has
 *    always used, drawn as every region lit. Individual marks are
 *    redundant beside it, so choosing it clears them, and touching one
 *    place afterwards starts precision over from that place.
 *
 * The selection reads back as TAGS under the figure — full words that
 * wrap, never a cropped column, pairs collapsed to their plain plural
 * ("Shoulders": on a body map, both marked already says both). A tag
 * is also the way to take a mark back.
 */
import React, { useEffect, useRef, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, { FadeInRight, runOnJS } from 'react-native-reanimated';
import * as Haptics from 'expo-haptics';
import { LOC_NAMES, readLocParts } from './model';
import { color, font } from './theme';

/* The silhouette and these regions share ONE coordinate system: the
   100 × 200 design space tools/make-body.js renders assets/body.png
   from. Change the figure there and the numbers here, together. */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const BODY = require('../assets/body.png');

interface Region {
  id: string;          // a LOC_NAMES id — several regions may share one
  side?: 'Left' | 'Right';
  x: number; y: number; w: number; h: number; r: number;
}

/* Left in these tables means the figure's anatomical left, which sits
   on the VIEWER'S right in the front view; the back view mirrors,
   exactly as a body does. Small joints lean on hitSlop — a sore wrist
   deserves a target bigger than a wrist. */
const mirrorX = (r: Omit<Region, 'id' | 'side'>) => ({ ...r, x: 100 - r.x - r.w });
const pairL = (idL: string, idR: string, r: Omit<Region, 'id' | 'side'>, front: boolean): Region[] => [
  { id: front ? idR : idL, side: front ? 'Right' : 'Left', ...r },
  { id: front ? idL : idR, side: front ? 'Left' : 'Right', ...mirrorX(r) },
];

function sideRegions(front: boolean): Region[] {
  const p = (l: string, r: string, box: Omit<Region, 'id' | 'side'>) => pairL(l, r, box, front);
  return ([] as Region[]).concat(
    p('shoulderL', 'shoulderR', { x: 28, y: 26.5, w: 16, h: 11, r: 5 }),
    p('armL', 'armR', { x: 22, y: 38, w: 11, h: 17, r: 5 }),
    p('elbowL', 'elbowR', { x: 21.5, y: 55, w: 11, h: 9, r: 4.5 }),
    p('forearmL', 'forearmR', { x: 21, y: 64, w: 11, h: 13, r: 4.5 }),
    p('wristL', 'wristR', { x: 20.5, y: 77, w: 10.5, h: 7, r: 3.5 }),
    p('handL', 'handR', { x: 18.5, y: 84, w: 11, h: 13, r: 5 }),
    p('hipL', 'hipR', { x: 35, y: 72, w: 15, h: 21, r: 7 }),
    p('thighL', 'thighR', { x: 36, y: 93, w: 13.5, h: 34, r: 6 }),
    p('kneeL', 'kneeR', { x: 37, y: 127, w: 12.5, h: 15, r: 6 }),
    p('calfL', 'calfR', { x: 38, y: 142, w: 11.5, h: 26, r: 5.5 }),
    p('ankleL', 'ankleR', { x: 38.5, y: 168, w: 11, h: 8, r: 4 }),
    p('footL', 'footR', { x: 34, y: 176, w: 15.5, h: 13, r: 6 }),
  );
}

const CENTRE: Region[] = [
  { id: 'head', x: 40, y: 1, w: 20, h: 20, r: 10 },
  { id: 'neck', x: 43, y: 20, w: 14, h: 8, r: 3.5 },
];

const FRONT: Region[] = CENTRE.concat(sideRegions(true), [
  { id: 'chest', x: 37.5, y: 36, w: 25, h: 20, r: 7 },
  { id: 'belly', x: 37.5, y: 56, w: 25, h: 17, r: 7 },
]);

const BACK: Region[] = CENTRE.concat(sideRegions(false), [
  { id: 'upperBack', x: 37.5, y: 36, w: 25, h: 20, r: 7 },
  { id: 'lowerBack', x: 37.5, y: 56, w: 25, h: 17, r: 7 },
]);

/** every place the body knows, both views — what an erase stroke works
 *  against when it starts from "all over" */
const ALL_IDS: string[] = (() => {
  const seen: Record<string, true> = {};
  const out: string[] = [];
  FRONT.concat(BACK).forEach((r) => {
    if (!seen[r.id]) { seen[r.id] = true; out.push(r.id); }
  });
  return out;
})();

export interface BodyMapProps {
  selected: string[];
  /** the whole next selection — the map owns toggle, stroke and
   *  all-over arithmetic so its rules live in one place */
  onChange: (next: string[]) => void;
  /** the check-in's pain colour — what a marked region wears */
  tint: string;
  /** legible ink on that colour, for the tags that sit on it */
  ink: string;
  /** the space the step actually has; the figure sizes itself to fit */
  containerWidth: number;
  containerHeight: number;
}

/** generous hit padding during a STROKE, in design units — a sweep down
 *  the arm should catch the wrist band without aiming. Taps keep the
 *  exact rects (plus hitSlop); only the moving finger gets the slack. */
const STROKE_PAD = 1.6;

export default function BodyMap({
  selected, onChange, tint, ink, containerWidth, containerHeight,
}: BodyMapProps) {
  /* Front/back as a toggle, not a rotation: two flat views ARE the
     clinical instrument, and a slider would be precision the record
     cannot store. */
  const [view, setView] = useState<'front' | 'back'>('front');
  /* fit: switch ~46pt, one tag line ~52pt; the figure takes the rest */
  const k = Math.max(1.4, Math.min(
    (containerHeight - 100) / 200,
    (containerWidth - 24) / 100
  ));
  const width = 100 * k;
  const regions = view === 'front' ? FRONT : BACK;
  const allOver = selected.indexOf('allOver') >= 0;

  const haptic = () => Haptics.selectionAsync().catch(() => {});

  const toggle = (id: string) => {
    haptic();
    if (allOver) {
      /* the whole body was marked; touching one place starts precision
         over from that place */
      onChange([id]);
      return;
    }
    onChange(selected.indexOf(id) >= 0
      ? selected.filter((x) => x !== id)
      : selected.concat(id));
  };

  /* All over IS the whole body: stored as the one id the record has
     always used, drawn as every region lit. */
  const toggleAllOver = () => {
    haptic();
    onChange(allOver ? [] : ['allOver']);
  };

  /* ── the stroke ───────────────────────────────────────────
     A ref mirrors the selection so a fast sweep is not throttled by
     render round-trips: each region paints against the stroke's own
     running state, and every change still flows up through onChange.

     The MODE is fixed at touch-down: starting on a marked region makes
     this an erasing sweep, on an unmarked one an adding sweep. An erase
     that starts from "all over" first materialises the whole body as
     explicit places and then removes what the finger crosses — "all
     over except my right knee" is a real thing to say, and this is the
     only honest way to say it. */
  const strokeSel = useRef<string[]>(selected);
  strokeSel.current = selected;
  const strokeMode = useRef<'add' | 'erase'>('add');
  const regionAt = (x: number, y: number): string | null => {
    const pad = STROKE_PAD * k;
    for (const rg of regions) {
      if (x >= rg.x * k - pad && x <= (rg.x + rg.w) * k + pad
        && y >= rg.y * k - pad && y <= (rg.y + rg.h) * k + pad) return rg.id;
    }
    return null;
  };
  const beginStroke = (x: number, y: number) => {
    const id = regionAt(x, y);
    const cur = strokeSel.current;
    const wasAllOver = cur.indexOf('allOver') >= 0;
    strokeMode.current = id && (wasAllOver || cur.indexOf(id) >= 0) ? 'erase' : 'add';
    if (strokeMode.current === 'erase' && wasAllOver) {
      strokeSel.current = ALL_IDS.slice();
      onChange(strokeSel.current);
    } else if (strokeMode.current === 'add' && wasAllOver) {
      strokeSel.current = [];
    }
    paintAt(x, y);
  };
  const paintAt = (x: number, y: number) => {
    const id = regionAt(x, y);
    if (!id) return;
    const cur = strokeSel.current;
    const has = cur.indexOf(id) >= 0;
    if (strokeMode.current === 'add' ? has : !has) return;
    const next = strokeMode.current === 'add'
      ? cur.concat(id)
      : cur.filter((x2) => x2 !== id);
    strokeSel.current = next;
    haptic();
    onChange(next);
  };
  const pan = Gesture.Pan()
    .minDistance(12)
    .onStart((e) => { 'worklet'; runOnJS(beginStroke)(e.x, e.y); })
    .onUpdate((e) => { 'worklet'; runOnJS(paintAt)(e.x, e.y); });

  /* Tags in ADD ORDER, newest rightmost — the selection array already
     records the order marks were made, so a stroke down the arm files
     Shoulder, Elbow, Wrist into the row as the finger passes. The row
     follows the newest tag so its arrival is always seen. */
  const parts = readLocParts(selected).slice().sort((a, b) => {
    const at = (p: { ids: string[] }) =>
      Math.max.apply(null, p.ids.map((id) => selected.indexOf(id)));
    return at(a) - at(b);
  });
  const tagScroll = useRef<ScrollView>(null);
  const prevCount = useRef(parts.length);
  useEffect(() => {
    if (parts.length > prevCount.current) {
      tagScroll.current?.scrollToEnd({ animated: true });
    }
    prevCount.current = parts.length;
  }, [parts.length]);

  return (
    <View style={styles.wrap}>
      <View style={styles.viewSwitch}>
        {(['front', 'back'] as const).map((v) => {
          const on = view === v;
          return (
            <Pressable
              key={v}
              onPress={() => { haptic(); setView(v); }}
              accessibilityRole="tab"
              accessibilityState={{ selected: on }}
              accessibilityLabel={v === 'front' ? 'Front of the body' : 'Back of the body'}
              style={({ pressed }) => [
                styles.viewItem, on && styles.viewItemOn, pressed && { opacity: 0.85 },
              ]}
            >
              <Text style={[styles.viewText, on && styles.viewTextOn]}
                allowFontScaling maxFontSizeMultiplier={1.3}>
                {v === 'front' ? 'Front' : 'Back'}
              </Text>
            </Pressable>
          );
        })}
      </View>

      <GestureDetector gesture={pan}>
        <View style={{ width, height: 200 * k, alignSelf: 'center' }}>
          <Image
            source={BODY}
            style={{ position: 'absolute', width, height: 200 * k }}
            resizeMode="stretch"
            accessible={false}
          />
          {regions.map((rg, i) => {
            const on = allOver || selected.indexOf(rg.id) >= 0;
            return (
              <Pressable
                key={rg.id + (rg.side || '') + i}
                onPress={() => toggle(rg.id)}
                hitSlop={rg.h < 10 ? 5 : 3}
                accessibilityRole="button"
                accessibilityState={{ selected: on }}
                accessibilityLabel={LOC_NAMES[rg.id] || rg.id}
                accessibilityHint={on ? 'Removes this area' : 'Marks this area'}
                style={({ pressed }) => [
                  {
                    position: 'absolute',
                    left: rg.x * k, top: rg.y * k,
                    width: rg.w * k, height: rg.h * k,
                    borderRadius: rg.r * k, borderCurve: 'continuous',
                  },
                  on && {
                    backgroundColor: tint, opacity: 0.92,
                    borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)',
                  },
                  pressed && !on && { backgroundColor: 'rgba(255,255,255,0.14)' },
                  pressed && on && { opacity: 0.65 },
                ]}
              />
            );
          })}
        </View>
      </GestureDetector>

      {/* ── the selection, as removable tags ────────────────
          ONE line that scrolls sideways, never a stack: a dozen marks
          must not pile into the Save button below. Full words, pairs
          collapsed; a tag is the selection made legible AND the way to
          take it back. */}
      <ScrollView
        ref={tagScroll}
        horizontal
        showsHorizontalScrollIndicator={false}
        style={styles.tagsScroll}
        contentContainerStyle={styles.tags}
        accessibilityLiveRegion="polite"
      >
        <Pressable
          onPress={toggleAllOver}
          accessibilityRole="button"
          accessibilityState={{ selected: allOver }}
          accessibilityLabel="All over"
          style={({ pressed }) => [
            styles.tag, styles.tagGhost,
            allOver && { backgroundColor: tint, borderColor: 'rgba(255,255,255,0.35)' },
            pressed && { opacity: 0.75 },
          ]}
        >
          <Text
            style={[styles.tagText, allOver && { color: ink, fontWeight: '700' as const }]}
            allowFontScaling maxFontSizeMultiplier={1.3}
          >
            All over
          </Text>
        </Pressable>
        {!allOver && parts.map((part) => (
          /* A new tag slides in from the right — the arrival is the
             confirmation that the touch landed. Entering only: a layout
             transition on the siblings fought the row's own
             scroll-to-end inside the centred scroll content and the two
             animations tore at each other. One mover at a time. */
          <Animated.View
            key={part.label}
            entering={FadeInRight.duration(220)}
          >
            <Pressable
              onPress={() => {
                haptic();
                onChange(selected.filter((x) => part.ids.indexOf(x) < 0));
              }}
              accessibilityRole="button"
              accessibilityLabel={part.label + ', marked'}
              accessibilityHint="Removes this area"
              style={({ pressed }) => [
                styles.tag,
                { backgroundColor: tint, borderColor: 'rgba(255,255,255,0.3)' },
                pressed && { opacity: 0.7 },
              ]}
            >
              <Text
                style={[styles.tagText, { color: ink, fontWeight: '600' as const }]}
                allowFontScaling maxFontSizeMultiplier={1.3}
                numberOfLines={1}
              >
                {part.label}
              </Text>
            </Pressable>
          </Animated.View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { flex: 1 },
  viewSwitch: {
    flexDirection: 'row', alignSelf: 'center', marginBottom: 12,
    backgroundColor: color.bgSegmentTrack, borderRadius: 11, borderCurve: 'continuous',
    padding: 2,
  },
  viewItem: {
    minWidth: 86, minHeight: 34, alignItems: 'center', justifyContent: 'center',
    borderRadius: 9, borderCurve: 'continuous', paddingHorizontal: 14,
  },
  viewItemOn: { backgroundColor: color.bgSegmentActive },
  viewText: { color: color.textSecondary, fontSize: font.subheadline, fontWeight: '600' },
  viewTextOn: { color: color.textPrimary },
  tagsScroll: { marginTop: 12, maxHeight: 40, flexGrow: 0 },
  /* real end-padding, so the last tag rests inside the row instead of
     being guillotined at the screen edge — a half-visible neighbour
     while SCROLLING is the affordance; a cropped final tag at rest is
     just a wound */
  tags: {
    flexDirection: 'row', gap: 7, alignItems: 'center',
    paddingHorizontal: 16, minWidth: '100%', justifyContent: 'center',
  },
  tag: {
    minHeight: 32, paddingHorizontal: 12, justifyContent: 'center',
    borderRadius: 16, borderCurve: 'continuous', borderWidth: 1,
  },
  tagGhost: { borderColor: color.borderControl, backgroundColor: color.bgSurface },
  tagText: { color: color.textPrimary, fontSize: font.footnote },
});
