/**
 * Pattern design tokens — single source of truth for the native app.
 * Values are lifted verbatim from the shipped PWA and the Figma
 * design system ("Pattern — Design System", collection "Pattern / Core").
 */

export const color = {
  bgRoot: '#000000',
  bgSheet: '#242426',
  bgSurface: '#1C1C1E',
  bgSegmentTrack: '#2C2C2E',
  bgSegmentActive: '#48484A',
  borderDivider: '#2E2E30',
  borderControl: '#3A3A3C',
  textPrimary: '#FFFFFF',
  textSecondary: '#A0A0A8',
  textTertiary: '#8E8E93',
  /** the soft terracotta this app uses for destructive TEXT — a warning
   *  that does not shout on a screen about pain */
  danger: '#E0795A',
  /** iOS systemRed, for the one place the platform's own colour is the
   *  clearer signal: the swipe-to-delete action, which people read by
   *  colour before they read the word */
  destructive: '#FF3B30',
  shieldOk: '#7CC9A6',
  /** the app's interactive tint — nav actions, links, selection */
  tint: '#5BA8FF',
  /** Pattern blue — the icon's rim, the brand's anchor hue */
  brand: '#0A84FF',
} as const;

/** The pain colour scale is a single brightness ramp of one hue:
 *  0 sits in near-black darkness and 10 is a luminous near-white — pain
 *  rises as luminosity, an amount rather than a verdict. Pure white is
 *  reserved for controls and selection, so 10 always stops short of it.
 *  Anchors are interpolated smoothly in painScale.painColor.
 *
 *  The HUE is the user's choice. Every theme keeps the same brightness
 *  story — anchors are channel-monotone, so luminance rises strictly from
 *  0 to 10 in every palette and the meaning of "brighter = more" never
 *  changes when the colour does. */
export type PainThemeId = 'blue' | 'violet' | 'rose' | 'mint' | 'violetPink';

export interface PainTheme {
  id: PainThemeId;
  name: string;
  /** the theme's saturated middle — today's ring, tinted accents */
  brand: string;
  anchors: ReadonlyArray<readonly [number, string]>;
}

/* ELEVEN STOPS, EVENLY SPACED (8 Sep 2026). The first ramps were five
   anchors mixed in sRGB, and on the calendar a 5, a 6 and a 7 were the
   same violet: measured in OKLab, the steps from 2 to 5 were about
   twice the size of the steps from 5 to 8, and chroma peaked at 5 and
   fell away on both sides, so the middle of the scale — where most
   days live — had the least contrast. Each theme keeps its 0, its 5
   and its 10 (the documented anchors, and the tests that pin them);
   the stops between are re-spaced so every neighbour differs by the
   same lightness, taking the theme's own hue and chroma at that
   lightness from the old ramp so blue still runs navy to sky and mint
   stays mint. Generated by tools/make-ramps.js — edit that, not these.
   Violet to pink is the same construction with the hue drifting about
   fifty degrees over the ramp: more separation for anyone who wants it,
   never red, offered and not imposed. */
export const PAIN_THEMES: readonly PainTheme[] = [
  {
    id: 'blue', name: 'Pattern Blue', brand: '#0A84FF',
    anchors: [
      [0, '#070C16'],
      [1, '#11213D'],
      [2, '#143869'],
      [3, '#115098'],
      [4, '#0E69CB'],
      [5, '#0A84FF'],
      [6, '#37A1FE'],
      [7, '#5CBAFE'],
      [8, '#8CD0FF'],
      [9, '#BEE3FE'],
      [10, '#EAF6FF'],
    ],
  },
  {
    id: 'violet', name: 'Violet', brand: '#BF5AF2',
    anchors: [
      [0, '#0E0714'],
      [1, '#261242'],
      [2, '#42216C'],
      [3, '#613195'],
      [4, '#8143C1'],
      [5, '#A455F0'],
      [6, '#B575F6'],
      [7, '#C692FC'],
      [8, '#D5B0FF'],
      [9, '#E4CEFE'],
      [10, '#F3EAFF'],
    ],
  },
  {
    id: 'violetPink', name: 'Violet to pink', brand: '#BF5AF2',
    anchors: [
      [0, '#0E0714'],
      [1, '#220E40'],
      [2, '#3E1366'],
      [3, '#5D1B88'],
      [4, '#7E29A5'],
      [5, '#9F3DBB'],
      [6, '#BE58CA'],
      [7, '#D976D5'],
      [8, '#EE99DE'],
      [9, '#FCBEE8'],
      [10, '#F3EAFF'],
    ],
  },
  {
    id: 'rose', name: 'Rose', brand: '#FF375F',
    anchors: [
      [0, '#14070B'],
      [1, '#3B1025'],
      [2, '#641B3B'],
      [3, '#91284F'],
      [4, '#BF3664'],
      [5, '#F0447A'],
      [6, '#F66D97'],
      [7, '#FB8EAF'],
      [8, '#FDAEC7'],
      [9, '#FECCDE'],
      [10, '#FFEAF4'],
    ],
  },
  {
    id: 'mint', name: 'Mint', brand: '#2AC0B0',
    anchors: [
      [0, '#071412'],
      [1, '#0E322E'],
      [2, '#13524B'],
      [3, '#1C756C'],
      [4, '#229A8D'],
      [5, '#2AC0B0'],
      [6, '#55CEC0'],
      [7, '#7DDACF'],
      [8, '#A2E6DD'],
      [9, '#C7F0EB'],
      [10, '#EAFBF8'],
    ],
  },
] as const;

export const DEFAULT_PAIN_THEME: PainThemeId = 'blue';

/** the default (blue) anchors — kept as a named export because the scale's
 *  documented contract is defined against them */
export const RAMP_ANCHORS = PAIN_THEMES[0].anchors;

/** semantic type scale — iOS text styles by name, in points. The system
 *  font (SF Pro on iOS) is the default family; Dynamic Type comes from
 *  allowFontScaling, which RN leaves on unless a style opts out. */
export const font = {
  largeTitle: 34,
  title1: 28,
  title2: 22,
  title3: 20,
  body: 17,
  subheadline: 15,
  footnote: 13,
} as const;

export type SlotKey = 'm' | 'd' | 'e';

/**
 * Corner radii, on Health's scale.
 *
 * A card at 16 is the radius of a LIST ROW's container, not of a card
 * you look at — beside Health's own the old value read tight and boxy.
 * Cards go to 20 and sheets to 24, which keeps the step between a
 * container and the controls inside it that Apple's own nesting has: a
 * child is always rounder-per-size than its parent is, never equal.
 *
 * Every one of these is drawn with borderCurve: 'continuous'. The number
 * was never the thing that made a corner look un-Apple — the curvature
 * was. iOS eases the corner into the straight edge; a plain circular arc
 * meets it at a tangent and reads pinched next to the real thing.
 */
export const radius = {
  button: 14,
  card: 26,
  sheet: 26,
  segment: 10,
  segmentTrack: 11,
} as const;

/* The page gutter and a card's own padding.
   Twenty points, which is what Apple Health leaves beside its own cards
   and what an inset grouped table uses on iPhone. Pattern sat at
   twenty-four, and beside Health the difference reads as this app being
   narrower rather than as this app being different — four points of
   nothing on both sides of every card, on the screen where the
   comparison is most likely to be made. */
const PAGE_X = 20;
const CARD_PAD = 16;

export const size = {
  buttonH: 52,
  rowH: 50,
  fab: 54,
  sliderThumb: 30,
  sliderTrackH: 6,
  pageX: PAGE_X,
  sheetX: 26,
  /** a card's own padding — every card in the app uses this one */
  cardPad: CARD_PAD,
  /** where WORDS start on a page whose first words are a card's title:
   *  the card's gutter plus the card's padding. Text set outside a card
   *  on such a page uses this, so the page has ONE left edge for reading
   *  rather than one inside cards and another between them. */
  contentX: PAGE_X + CARD_PAD,
} as const;
